echo ""
echo "==> IMPORTANTE: configura le API key"
echo "   Registrati su https://openrouter.ai e ottieni le chiavi."
echo "   Poi aggiungi a ~/.bashrc:"
echo "     export WHISPER_API_KEY='sk-or-v1-...'  # per trascrizione Whisper"
echo "     export WHISPER_API_BASE='https://openrouter.ai/api/v1'"
echo "     export OPENAI_API_KEY='sk-or-v1-...'   # per generazione comandi Sgpt"
echo "     export OPENAI_API_BASE='https://openrouter.ai/api/v1'"
echo ""
echo "   esegui source ~/.bashrc per aggiornare environment"
echo ""

echo "==> Installazione completata!"
echo ""
echo "  usa sgpt config show per vedere la configurazione di shellgpt"
echo "  usa sgpt check per assicurarti che shellgpt sia correttamente configurato"
echo ""
echo "==> Per avviare l'applicazione:"
echo "  source venv/bin/activate"
echo "  python main.py"
